apiVersion: apps/v1
kind: Deployment
metadata:
  name: unhappy-camper
spec:
  selector:
    matchLabels:
      app: whatever
  replicas: 1
  template:
    metadata:
      labels:
        app: whatever
    spec:
      containers:
        - name: shell
          image: centos:7
          command:
            - sh
            - '-c'
            - tail -f /dev/null
